### PR TITLE
System Notifications for WidePoint

### LINKED ISSUE #944: System Notification for: WidePoint SSP
- notice_date: May 8, 2024
  change_type: Intent to Modify a CA Certificate
  system: WidePoint SSP
  change_description: The WidePoint SSP Intermediate CA intends to issue a modified certificate to the U.S. Department of Transportation Agency CA G6 on or about 5/22/2024. Once the new certificate is accepted and published, the previous certificate will be revoked.
  contact: WCSC-PKIPolicy at widepoint dot com
  ca_certificate_hash: 69e17e8c900f3f853e16f05fc2a45e7941ef5d29
  ca_certificate_issuer: CN = WidePoint SSP Intermediate CA, O=ORC PKI, C=US
  ca_certificate_subject: CN = U.S. Department of Transportation Agency CA G6, OU = U.S. Department of Transportation, O = U.S. Government, C=US
  cdp_uri: http://crl-server.orc.com/CRLs/WPSSPIntCA.crl
  aia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedToWPSSPIntCA.p7c
  sia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedByWPSSPIntCA.p7c
  ocsp_uri: N/A
  ee_cdp_uri: http://crl-server.orc.com/CRLs/DoTAgencyCAG6.crl
  ee_ocsp_uri: http://dotagencyg6.eva.orc.com/

- notice_date: May 8, 2024
  change_type: Intent to Modify a CA Certificate
  system: WidePoint SSP
  change_description: The WidePoint SSP Intermediate CA intends to issue a modified certificate to the U.S. Department of Transportation Device CA G6 on or about 5/22/2024. Once the new certificate is accepted and published, the previous certificate will be revoked.
  contact: WCSC-PKIPolicy at widepoint dot com
  ca_certificate_hash: 4638aa1b34ed72deb2de3aab780291f3bb70d3f5
  ca_certificate_issuer: CN = WidePoint SSP Intermediate CA, O=ORC PKI, C=US
  ca_certificate_subject: CN = U.S. Department of Transportation Device CA G6, OU = U.S. Department of Transportation, O = U.S. Government, C=US
  cdp_uri: http://crl-server.orc.com/CRLs/WPSSPIntCA.crl
  aia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedToWPSSPIntCA.p7c
  sia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedByWPSSPIntCA.p7c
  ocsp_uri: http://ssp5.eva.orc.com
  ee_cdp_uri: http://crl-server.orc.com/CRLs/DoTDeviceCAG6.crl
  ee_ocsp_uri: http://dotdeviceg6.eva.orc.com/

- notice_date: May 8, 2024
  change_type: Intent to Revoke a CA Certificate
  system: WidePoint SSP
  change_description: The WidePoint SSP Intermediate CA intends to revoke a CA certificate issued to the U.S. Department of Transportation Agency CA G6 on or about 5/29/2024. This certificate is being replaced by a modified CA certificate.
  contact: WCSC-PKIPolicy at widepoint dot com
  ca_certificate_hash: 7b6dcb34ab284ec897f0ffe1a2f8f95082f09c74
  ca_certificate_issuer: CN = WidePoint SSP Intermediate CA, O=ORC PKI, C=US
  ca_certificate_subject: CN = U.S. Department of Transportation Agency CA G6, OU = U.S. Department of Transportation, O = U.S. Government, C=US
  cdp_uri: http://crl-server.orc.com/CRLs/WPSSPIntCA.crl
  aia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedToWPSSPIntCA.p7c
  sia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedByWPSSPIntCA.p7c
  ocsp_uri: N/A
  ee_cdp_uri: http://crl-server.orc.com/CRLs/DoTAgencyCAG6.crl
  ee_ocsp_uri: http://dotagencyg6.eva.orc.com/

- notice_date: May 8, 2024
  change_type: Intent to Revoke a CA Certificate
  system: WidePoint SSP
  change_description: The WidePoint SSP Intermediate CA intends to revoke a CA certificate issued to the U.S. Department of Transportation device CA G6 on or about 5/29/2024. This certificate is being replaced by a modified CA certificate.
  contact: WCSC-PKIPolicy at widepoint dot com
  ca_certificate_hash: e0f1bd791fe607a6a3b1f5528eab4687dbbb9dce
  ca_certificate_issuer: CN = WidePoint SSP Intermediate CA, O=ORC PKI, C=US
  ca_certificate_subject: CN = U.S. Department of Transportation Device CA G6, OU = U.S. Department of Transportation, O = U.S. Government, C=US
  cdp_uri: http://crl-server.orc.com/CRLs/WPSSPIntCA.crl
  aia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedToWPSSPIntCA.p7c
  sia_uri: http://crl-server.orc.com/caCerts/caCertsIssuedByWPSSPIntCA.p7c
  ocsp_uri: N/A
  ee_cdp_uri: http://crl-server.orc.com/CRLs/DoTDeviceCAG6.crl
  ee_ocsp_uri: http://dotdeviceg6.eva.orc.com/

### PR DESCRIPTION
**Pull request by dproudGSA**
Closes #944 (date on the issue is wrong. Should be May 8, not April 8)

### CODE REVIEW

**Comment by dproudGSA** [comment]
I can't see what it says under "details" to figure out what the problem is.

**Review by JBPayne007 — APPROVED** [review]

**Comment by JBPayne007** [comment]
There was a problem running Jekyll when pages/build. Please correct this issue.

2024-05-09 10:53:08 INFO [setup-bundler] `` is not a directory.
2024-05-09 10:53:08 INFO [setup-bundler] Bundler will use `/tmp/bundler20240509-3327-3v7th23327' as your home directory temporarily.
2024-05-09 10:53:08 INFO [setup-bundler] Bundle complete! 12 Gemfile dependencies, 46 gems now installed.
2024-05-09 10:53:08 INFO [setup-bundler] Use `bundle info [gemname]` to see where a bundled gem is installed.
2024-05-09 10:53:08 INFO [setup-bundler] 1 installed gem you directly depend on is looking for funding.
2024-05-09 10:53:09 INFO [build-jekyll] Building using Jekyll version: jekyll 4.2.2
2024-05-09 10:53:09 INFO [build-jekyll] Now using node v18.19.1 (npm v10.2.4)
2024-05-09 10:53:10 INFO [build-jekyll] Configuration file: /tmp/work/site_repo/_config.yml
2024-05-09 10:53:10 INFO [build-jekyll] Source: /tmp/work/site_repo
2024-05-09 10:53:10 INFO [build-jekyll] Destination: /tmp/work/site_repo/_site
2024-05-09 10:53:10 INFO [build-jekyll] Incremental build: disabled. Enable with --incremental
2024-05-09 10:53:10 INFO [build-jekyll] Generating...
2024-05-09 10:53:10 INFO [build-jekyll] cp -r node_modules/@uswds/uswds/dist/js/ assets/
2024-05-09 10:53:10 INFO [build-jekyll] cp -r node_modules/@uswds/uswds/dist/img/ assets/
2024-05-09 10:53:10 INFO [build-jekyll] cp -r node_modules/@uswds/uswds/dist/fonts/ assets/
2024-05-09 10:53:10 INFO [build-jekyll] [31m                    ------------------------------------------------[0m
2024-05-09 10:53:10 INFO [build-jekyll] [31m      Jekyll 4.2.2   Please append `--trace` to the `build` command [0m
2024-05-09 10:53:10 INFO [build-jekyll] [31m                     for any additional information or backtrace. [0m
2024-05-09 10:53:10 INFO [build-jekyll] [31m                    ------------------------------------------------[0m
2024-05-09 10:53:10 ERROR [main] There was a problem running Jekyll, see the above logs for details.

**Comment by dproudGSA** [comment]
@JBPayne007 Is there any way I can get access so I can see these errors in GitHub rather than the screenshot? I need to see these errors in context.

**Comment by JBPayne007** [comment]
These error are not within GitHub. It is an error with pages/build or cloud.gov where the page is built and the screenshot is from that application. You should be able to click on the icon and logon with your GSA account is an option.

**Pull request closed without merging**
